# Quiz Support Vector Machines
### Starter Code
Ilyas Ustun    

- In this exercise we will predict whether a person is a drug user.  
- The class 1 in variable y indicates a person is drug user, while 0 indicates the opposite.    
- The variables atrting with "x" are going to be the input variables.

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn import model_selection
from sklearn import svm
from sklearn.model_selection import GridSearchCV

In [10]:
df = pd.read_csv('drug_use.csv')

In [3]:
df.head()

id       x1       x2       x3       x4       x5       x6       x7       x8  \
0   1  0.49788  0.48246 -0.05921  0.96082  0.12600  0.31287 -0.57545 -0.58331   
1   2 -0.07854 -0.48246  1.98437  0.96082 -0.31685 -0.67825  1.93886  1.43533   
2   3  0.49788 -0.48246 -0.05921  0.96082 -0.31685 -0.46725  0.80523 -0.84732   
3   4 -0.95197  0.48246  1.16365  0.96082 -0.31685 -0.14882 -0.80615 -0.01928   
4   5  0.49788  0.48246  1.98437  0.96082 -0.31685  0.73545 -1.63340 -0.45174   

        x9      x10      x11      x12  y  
0 -0.91699 -0.00665 -0.21712 -1.18084  0  
1  0.76096 -0.14277 -0.71126 -0.21575  1  
2 -1.62090 -1.01450 -1.37983  0.40148  0  
3  0.59042  0.58489 -1.37983 -1.18084  0  
4 -0.30172  1.30612 -0.21712 -0.21575  0

In [9]:
df.sum()

id     1.781881e+06
x1     6.523976e+01
x2    -4.824600e-01
x3    -7.174480e+00
x4     6.701970e+02
x5    -5.835530e+02
x6     8.785000e-02
x7    -3.068800e-01
x8    -1.007340e+00
x9    -4.617600e-01
x10   -7.277400e-01
x11    1.360228e+01
x12   -6.204790e+00
y      1.060000e+03
dtype: float64

In [11]:
df.isnull().sum()

id     0
x1     0
x2     0
x3     0
x4     0
x5     0
x6     0
x7     0
x8     0
x9     0
x10    0
x11    0
x12    0
y      0
dtype: int64

In [5]:
sum(y)

1060

In [12]:
X = df.drop(['id', 'y'], axis=1)
y = df.y

In [13]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.33, random_state=42)
X_train, X_val, y_train, y_val = model_selection.train_test_split(X_train, y_train, test_size=0.33, random_state=42)

In [14]:
from sklearn import svm

In [24]:
svc = svm.SVC(kernel='linear')
svc

SVC(kernel='linear')

In [25]:
svc.fit(X_train, y_train)

SVC(kernel='linear')

In [17]:
svc.score(X_train, y_train)

0.7136094674556213

In [23]:
svc.support_vectors_

array([[-0.07854,  0.48246,  0.45468, ..., -1.13788,  0.88113,  0.40148],
       [ 1.09449, -0.48246, -1.22751, ...,  0.58489, -0.71126, -0.52593],
       [ 1.09449, -0.48246,  1.16365, ..., -0.14277,  0.19268, -0.52593],
       ...,
       [-0.95197, -0.48246, -0.61113, ...,  0.58489,  1.29221,  0.40148],
       [ 0.49788,  0.48246,  1.16365, ...,  1.13407, -0.71126, -0.84637],
       [ 0.49788,  0.48246, -0.61113, ..., -0.52745, -0.71126,  0.07987]])

In [32]:
svc.support_

array([  1,   4,   5,  10,  20,  22,  24,  27,  28,  30,  32,  35,  40,
        45,  46,  48,  49,  50,  52,  54,  59,  60,  62,  69,  71,  72,
        75,  81,  88, 100, 102, 107, 110, 113, 115, 117, 121, 122, 123,
       125, 133, 136, 141, 142, 145, 146, 148, 149, 152, 154, 164, 168,
       169, 171, 177, 190, 200, 202, 203, 218, 224, 225, 229, 234, 242,
       243, 244, 245, 246, 249, 252, 256, 259, 260, 261, 265, 267, 273,
       274, 278, 281, 282, 284, 287, 292, 293, 298, 300, 301, 302, 303,
       306, 309, 310, 311, 316, 317, 322, 323, 325, 326, 335, 339, 340,
       341, 344, 345, 347, 348, 349, 351, 354, 357, 358, 364, 369, 371,
       372, 380, 382, 384, 386, 388, 399, 403, 407, 409, 411, 412, 415,
       417, 418, 421, 423, 426, 431, 432, 437, 438, 444, 445, 447, 449,
       456, 460, 461, 464, 470, 475, 477, 479, 486, 492, 493, 494, 495,
       496, 497, 504, 506, 508, 512, 514, 515, 519, 520, 521, 524, 529,
       530, 531, 536, 537, 539, 542, 544, 549, 551, 556, 561, 56

In [33]:
svc.n_support_

array([280, 281], dtype=int32)

In [38]:
len(svc.support_)

561

In [73]:
parameters = {'C':[0.00001, 0.0001, 0.001, 0.01, 1, 10]}
searcher = GridSearchCV(svc, parameters)
searcher.fit(X_train, y_train)

GridSearchCV(estimator=SVC(kernel='linear'),
             param_grid={'C': [1e-05, 0.0001, 0.001, 0.01, 1, 10]})

In [74]:
print("Best CV params", searcher.best_params_)
print("Best CV accuracy", searcher.best_score_)

Best CV params {'C': 0.01}
Best CV accuracy 0.7005917159763314


In [87]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.svm import SVC

tuned_parameters = [
    #{"kernel": ["rbf"], "gamma": [0.01, 0.1, 1], "C": [0.01, 0.1, 1, 10]},
    {"kernel": ["linear"], "C": [0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10]},
]

scores = ["precision", "recall"]

for score in scores:
    print("# Tuning hyper-parameters for %s" % score)
    print()

    clf = GridSearchCV(SVC(), tuned_parameters, cv = 3, scoring="%s_macro" % score)
    clf.fit(X_train, y_train)

    print("Best parameters set found on development set:")
    print()
    print(clf.best_params_)
    print()
    print("Grid scores on development set:")
    print()
    means = clf.cv_results_["mean_test_score"]
    stds = clf.cv_results_["std_test_score"]
    for mean, std, params in zip(means, stds, clf.cv_results_["params"]):
        print("%0.3f (+/-%0.03f) for %r" % (mean, std * 2, params))
    print()

    print("Detailed classification report:")
    print()
    print("The model is trained on the full development set.")
    print("The scores are computed on the full evaluation set.")
    print()
    y_true, y_pred = y_test, clf.predict(X_test)
    print(classification_report(y_true, y_pred))
    print()


# Tuning hyper-parameters for precision



/Users/serenayang/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/serenayang/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/serenayang/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/serenayang/opt/anaconda3/lib/python3

Best parameters set found on development set:

{'C': 0.001, 'kernel': 'linear'}

Grid scores on development set:

0.282 (+/-0.001) for {'C': 1e-05, 'kernel': 'linear'}
0.282 (+/-0.001) for {'C': 0.0001, 'kernel': 'linear'}
0.700 (+/-0.237) for {'C': 0.001, 'kernel': 'linear'}
0.695 (+/-0.030) for {'C': 0.01, 'kernel': 'linear'}
0.685 (+/-0.016) for {'C': 0.1, 'kernel': 'linear'}
0.687 (+/-0.020) for {'C': 1, 'kernel': 'linear'}
0.690 (+/-0.023) for {'C': 10, 'kernel': 'linear'}

Detailed classification report:

The model is trained on the full development set.
The scores are computed on the full evaluation set.

              precision    recall  f1-score   support

           0       0.79      0.32      0.45       276
           1       0.63      0.93      0.75       347

    accuracy                           0.66       623
   macro avg       0.71      0.62      0.60       623
weighted avg       0.70      0.66      0.62       623


# Tuning hyper-parameters for recall

Best parameter

In [71]:
parameters = {'C':[0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10], 'gamma':[0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10 ,100, 1000]}
searcher = GridSearchCV(svc, parameters, cv = 3)
searcher.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=SVC(kernel='linear'),
             param_grid={'C': [1e-05, 0.0001, 0.001, 0.01, 0.1, 1, 10],
                         'gamma': [1e-05, 0.0001, 0.001, 0.01, 0.1, 1, 10, 100,
                                   1000]})

In [72]:
print("Best CV params", searcher.best_params_)
print("Best CV accuracy", searcher.best_score_)

Best CV params {'C': 0.01, 'gamma': 1e-05}
Best CV accuracy 0.699406038885103


In [70]:
from sklearn.svm import SVC
C_2d_range = [0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10]
gamma_2d_range = [0.1]
classifiers = []
for C in C_2d_range:
    for gamma in gamma_2d_range:
        clf = SVC(C=C, kernel ='rbf', gamma=gamma)
        clf.fit(X_train, y_train)
        classifiers.append((C,clf))
print(classifiers)

[(1e-05, SVC(C=1e-05, gamma=0.1)), (0.0001, SVC(C=0.0001, gamma=0.1)), (0.001, SVC(C=0.001, gamma=0.1)), (0.01, SVC(C=0.01, gamma=0.1)), (0.1, SVC(C=0.1, gamma=0.1)), (1, SVC(C=1, gamma=0.1)), (10, SVC(C=10, gamma=0.1))]


In [62]:
from sklearn.svm import SVC
C_2d_range = [0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10]
classifiers = []
for C in C_2d_range:
    clf = SVC(C=C)
    clf.fit(X_train, y_train)
    classifiers.append((C, clf))


TypeError: 'SVC' object is not callable

In [57]:
print(classifiers)

[(1e-05, 0.1, SVC(C=1e-05, gamma=0.1)), (0.0001, 0.1, SVC(C=0.0001, gamma=0.1)), (0.001, 0.1, SVC(C=0.001, gamma=0.1)), (0.01, 0.1, SVC(C=0.01, gamma=0.1)), (0.1, 0.1, SVC(C=0.1, gamma=0.1)), (1, 0.1, SVC(C=1, gamma=0.1)), (10, 0.1, SVC(C=10, gamma=0.1))]


In [52]:
C_range = np.logspace(0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10)
gamma_range = np.logspace(0.1)
param_grid = dict(gamma=gamma_range, C=C_range)
cv = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=42)
grid = GridSearchCV(SVC(), param_grid=param_grid, cv=cv)
grid.fit(X_train, y_train)

print(
    "The best parameters are %s with a score of %0.2f"
    % (grid.best_params_, grid.best_score_)
)

TypeError: 'float' object cannot be interpreted as an integer